---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JohnZhang.
--- DateTime: 2025/5/1 14:56
---

-- KEYS[1]: 库存 key
-- ARGV[1]: 扣减数量
local stock = tonumber(redis.call('GET', KEYS[1]))
local qty = tonumber(ARGV[1])
if stock >= qty then
    redis.call('DECRBY', KEYS[1], qty)
    return 1
else
    return 0
end
